export const TEXT_BUTTON = {
  SEARCH: "ค้นหา",
  CLEAR: "ล้างค่า",
  ADD: "เพิ่ม",
  EDIT: "แก้ไข",
  DELETE: "ลบ",
  SAVE: "บันทึก",
  CANCEL: "ยกเลิก",
  CONFIRM: "ยืนยัน",
  APPROVE: "อนุมัติ",
  REJECT: "ปฏิเสธ",
  EXPORT: "ส่งออก",
  IMPORT: "นำเข้า",
  CLOSE: "ปิด",
  BACK: "ย้อนกลับ",
  NEXT: "ถัดไป",
  VIEW_ALL: "ดูทั้งหมด",
  LOGIN: "เข้าสู่ระบบ",
  LOGOUT: "ออกจากระบบ",
  RESET_PASSWORD: "รีเซ็ตรหัสผ่าน",
  ENABLE: "เปิดใช้งาน",
  DISABLE: "ปิดใช้งาน",
  UNLOCK: "ปลดล็อก",
  LOCK: "ล็อก",
} as const;
